Landing and products
Ryhthmic-Squad/grace-shopper pull request #47
Opened 2021-05-06 12:50 UTC by Michelle-Martin

This PR has the singleProduct and AllProducts components along with their styled components files.

2021-05-06 12:53 UTC, Michelle-Martin commented
this is the travis error I am getting: 

console.error
    Error: bad credentials
        at Function.Object.<anonymous>.User.authentication (/home/travis/build/Ryhthmic-Squad/grace-shopper/server/db/User.js:111:21)
        at /home/travis/build/Ryhthmic-Squad/grace-shopper/server/api/Auth.js:14:19
      29 |
      30 | app.use((er, req, res, next) => {
    > 31 |   console.error(er.stack);
         |           ^
      32 |   res.status(er.status || 500).send({ error: er.message });
      33 | });
      34 |

2021-05-07 00:00 UTC, justinmattos requested changes

2021-05-07 00:00 UTC, justinmattos commented on client/index.js
> +  </BrowserRouter>,
Can you undo this change? We switched to HashRouter and put it in the Main component rather than out here.

2021-05-07 00:00 UTC, justinmattos commented on client/index.js
> +import AllUsers from './Containers/Admin/AllUsers.jsx';
We also don't need these here either

2021-05-07 00:00 UTC, justinmattos commented on client/Containers/Main.jsx
> +          <Route component={SingleProduct} path="/products/:id" exact />
I think we still want the `<Switch>` around all the routes

2021-05-07 00:25 UTC, vikkiwchan commented on client/Containers/SingleProduct.jsx
> +              'Out of stock'
Let me know if you need me to show your how to add the add to cart thunk

2021-05-07 02:51 UTC, justinmattos requested changes

2021-05-07 02:51 UTC, justinmattos commented on client/index.js
> -);
While we no longer want `<BrowserRouter>` here, we still need some of this to mount our react app:
```javascript
ReactDOM.render(
  <Provider store={store}>
    <Global Style />
    <Main />
  </Provider>,
  document.getElementById('root')
);
```

2021-05-07 03:48 UTC, merged